package zkcrypto

import (
	"crypto/sha256"
	"encoding/base64"
	"strings"
	"testing"
)

// formatSecretKeyForTest mirrors recoveryCredential.ts's
// generateRecoverySecretKey formatting step (base32-encode raw+checksum,
// group into 4-char blocks) -- test-only, not exported.
func formatSecretKeyForTest(raw []byte) (string, error) {
	digest := sha256.Sum256(raw)
	payload := append(append([]byte{}, raw...), digest[0])
	encoded := base32Encoding.EncodeToString(payload)
	var groups []string
	for i := 0; i < len(encoded); i += 4 {
		end := i + 4
		if end > len(encoded) {
			end = len(encoded)
		}
		groups = append(groups, encoded[i:end])
	}
	return strings.Join(groups, "-"), nil
}

// This test vector was generated from a standalone Node script using the
// same WebCrypto primitives (crypto.subtle) the browser's
// recoveryCredential.ts/accountCrypto.ts actually call -- see the plan's
// verification section. It is NOT a byte-for-byte extract of that TS
// file's own execution, but exercises identical algorithm/parameter
// choices (PBKDF2-HMAC-SHA256, HKDF-SHA256 with the same two info
// strings, AES-GCM with a 12-byte IV and split ciphertext/tag). Passing
// this test means the Go port derives byte-identical key material for
// the pbkdf2 branch; it does not by itself prove the real TS file
// wasn't changed independently -- see Verification in the approved plan
// for the follow-up: cross-check directly against the ZK test account
// (LOCAL_ZK_TEST_* in local-test-user.env) via the real browser.
func TestDeriveKek_PBKDF2_MatchesWebCryptoVector(t *testing.T) {
	secretKeyRaw, err := base64.StdEncoding.DecodeString("AwoRGB8mLTQ7QklQV15lbA==")
	if err != nil {
		t.Fatal(err)
	}
	params := KdfParams{
		Algorithm:  "pbkdf2",
		Salt:       "34w4eauhLAJCx0qXhz0yrrWISQc5nzqaMM7hJigVYN8=",
		Iterations: 100_000,
	}
	passphrase := "correct horse battery staple zebra"

	kek, err := DeriveKek(passphrase, secretKeyRaw, params)
	if err != nil {
		t.Fatal(err)
	}
	wantKek := "cpaS5I+ClEMHpWNBA1D9ptSrDvABLI7BCQWzUNJx6qE="
	if got := base64.StdEncoding.EncodeToString(kek); got != wantKek {
		t.Errorf("KEK mismatch:\n got  %s\n want %s", got, wantKek)
	}

	verifier, err := DeriveVerifierHash(passphrase, secretKeyRaw, params)
	if err != nil {
		t.Fatal(err)
	}
	wantVerifier := "84NvXW4TnQu5VgxVSS8CTkbrzMIS7sGzhlfcntZLdaI="
	if verifier != wantVerifier {
		t.Errorf("verifier hash mismatch:\n got  %s\n want %s", verifier, wantVerifier)
	}

	// Decrypt a title envelope that was encrypted (by the Node script)
	// under this exact KEK -- confirms AES-GCM decrypt (ciphertext/tag
	// split, IV handling) is also byte-compatible, not just the KDF/HKDF
	// chain above.
	titleEnvelope := `{"ciphertext":"KuPUQXjW0xi3e0GXgXN+aU9RN9RQ+R/U","iv":"6szJ9ctH3QCCQLuO","tag":"wp5ZwyNW6VHGilIDIRE3PA=="}`
	title, err := DecryptString(kek, titleEnvelope)
	if err != nil {
		t.Fatal(err)
	}
	if want := "Zero-Knowledge test note"; title != want {
		t.Errorf("decrypted title = %q, want %q", title, want)
	}
}

func TestParseRecoverySecretKey_RoundTrip(t *testing.T) {
	// A key generated and formatted the same way
	// recoveryCredential.ts's generateRecoverySecretKey would (16 raw
	// bytes + a SHA-256-derived checksum byte, base32, grouped by 4).
	raw, err := base64.StdEncoding.DecodeString("AwoRGB8mLTQ7QklQV15lbA==")
	if err != nil {
		t.Fatal(err)
	}
	// Checksum byte computed the same way ParseRecoverySecretKey expects
	// (first byte of SHA-256(raw)) -- computed independently here via the
	// package's own primitives isn't circular since we're testing the
	// parse/checksum-verify path, not re-deriving it from DeriveKek.
	formatted, err := formatSecretKeyForTest(raw)
	if err != nil {
		t.Fatal(err)
	}
	parsed, err := ParseRecoverySecretKey(formatted)
	if err != nil {
		t.Fatalf("ParseRecoverySecretKey(%q) failed: %v", formatted, err)
	}
	if base64.StdEncoding.EncodeToString(parsed) != base64.StdEncoding.EncodeToString(raw) {
		t.Errorf("round-tripped raw bytes don't match")
	}

	if _, err := ParseRecoverySecretKey("NOT-A-VALID-KEY"); err == nil {
		t.Error("expected an error for a garbage Secret Key, got nil")
	}
}

// This test vector was generated by loading the exact libsodium-wrappers-
// sumo build gcp-note-taking-frontend bundles (node_modules/libsodium-sumo
// + libsodium-wrappers-sumo, the "sumo" build specifically -- see
// recoveryCredential.ts's comment: the plain libsodium-wrappers build
// omits crypto_pwhash/Argon2id entirely) into a real Chromium page via
// Playwright (about:blank isn't a secure context, so window.crypto.subtle
// is unavailable there -- a real localhost page was used instead) and
// running crypto_pwhash + the same HKDF-SHA256 combine recoveryCredential.ts
// uses. This confirms golang.org/x/crypto/argon2.IDKey and libsodium's
// crypto_pwhash(ALG_ARGON2ID13) agree byte-for-byte given identical
// params (opsLimit=time, memLimitKib=memory, threads=1) -- the one thing
// that was previously unverified (see git history/PR description for the
// throwaway script used to generate this).
func TestDeriveKek_Argon2id_MatchesLibsodiumVector(t *testing.T) {
	secretKeyRaw, err := base64.StdEncoding.DecodeString("AwoRGB8mLTQ7QklQV15lbA==")
	if err != nil {
		t.Fatal(err)
	}
	params := KdfParams{
		Algorithm: "argon2id",
		Salt:      "8sTligLmjGbZVmgSCqt/rQ==",
		Ops:       1,
		MemoryKiB: 8,
	}
	passphrase := "correct horse battery staple zebra"

	kek, err := DeriveKek(passphrase, secretKeyRaw, params)
	if err != nil {
		t.Fatal(err)
	}
	wantKek := "4IT7RuAZpBWJ+UhaNd7GRUia1LNMVGXcRZXLR8nsjFQ="
	if got := base64.StdEncoding.EncodeToString(kek); got != wantKek {
		t.Errorf("KEK mismatch:\n got  %s\n want %s", got, wantKek)
	}

	verifier, err := DeriveVerifierHash(passphrase, secretKeyRaw, params)
	if err != nil {
		t.Fatal(err)
	}
	wantVerifier := "KAAclQRfcS7Dq9xUBusFFhIjRGdSRCKfxfvuAjxmsVM="
	if verifier != wantVerifier {
		t.Errorf("verifier hash mismatch:\n got  %s\n want %s", verifier, wantVerifier)
	}

	titleEnvelope := `{"ciphertext":"y40Q4ACy/uGHbX/tzaR/5Jh4B1Rj1yK5","iv":"ly2Ww7LUXWvZIoa6","tag":"PzpvDxGDUw+/9IPt+k3wuA=="}`
	title, err := DecryptString(kek, titleEnvelope)
	if err != nil {
		t.Fatal(err)
	}
	if want := "Zero-Knowledge test note"; title != want {
		t.Errorf("decrypted title = %q, want %q", title, want)
	}
}
